cpp00:
  ex00:
    name: megaphone
    tests:
      - VALGRIND
      - VALGRIND can you fucking hear me?!
      - VALGRIND "what about" "strings?"
  ex01:
    name: phonebook
    tests:
      - echo -e "bleurgh\nADD\n\nfirst\nlast\nnick\n123\nyou'll never know\nSEARCH\n1\nb\n0\nEXIT\n" | VALGRIND

cpp01:
  ex00:
    name: brainz
    tests:
      - VALGRIND
  ex01:
    name: horde
    tests:
      - VALGRIND
  ex02:
    name: hi
    tests:
      - VALGRIND
  ex03:
    name: weapons
    tests:
      - VALGRIND
  ex04:
    name: replace
    tests:
      - echo "hello how are you?" > tmp.txt; VALGRIND tmp.txt " " "_" END; rm -f tmp.txt
      - echo -n "" > tmp.txt; VALGRIND tmp.txt " " "_" END; rm -f tmp.txt
      - echo "this is a test with no match" > tmp.txt; VALGRIND tmp.txt "strawberry" "jam" END; rm -f tmp.txt
  ex05:
    name: complain
    tests:
      - VALGRIND

cpp02:
  ex00:
    name: fixed
    tests:
      - VALGRIND
  ex01:
    name: fixed
    tests:
      - VALGRIND
  ex02:
    name: fixed
    tests:
      - VALGRIND

cpp03:
  ex00:
    name: claptrap
    tests:
      - VALGRIND
  ex01:
    name: scavtrap
    tests:
      - VALGRIND
  ex02:
    name: fragtrap
    tests:
      - VALGRIND

cpp04:
  ex00:
    name: animal
    tests:
      - VALGRIND
  ex01:
    name: brain
    tests:
      - VALGRIND
  ex02:
    name: abstract
    tests:
      - VALGRIND
  ex03:
    name: interfaces
    tests:
      - VALGRIND

cpp05:
  ex00:
    name: bureaucrat
    tests:
      - VALGRIND
  ex01:
    name: form
    tests:
      - VALGRIND
  ex02:
    name: forms
    tests:
      - VALGRIND

cpp06:
  ex00:
    name: conversion
    tests:
      - VALGRIND 5
      - VALGRIND nan
      - VALGRIND -3.14f
      - VALGRIND inff
      - VALGRIND 4.2
  ex01:
    name: data
    tests:
      - VALGRIND

